name: DarkAuction
main: mc.alessandroch.darkauction.DarkAuction
version: 1.3.4
description: DarkAuction system similar to hypixel auction
author: AlessandroCH
softdepend: [ Vault,DecentHolograms ]
api-version: 1.19
commands:
  darkauction:
    description: Admin command for manage the plugin
    permission: darkauction.darkauction
  openauction:
    description: Command for open the auction
    permission: darkauction.openauction

     
     
